version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - ./backend/.env
    networks:
      - backend

  redis:
    image: redis
    restart: always
    networks:
      - backend


  mysql:
    image: mysql
    restart: always

    env_file:
      - ./backend/.env

    networks:
      - backend

  backend:
    build:
      context: ../
      dockerfile: ./exec/backend/dockerfile
    env_file:
      - ./backend/.env

    restart: always
    networks:
      - backend
      - nat

  nginx:
    build:
      context: ../
      dockerfile: ./exec/frontend/dockerfile

    env_file:
      - ./frontend/.env

    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./frontend/conf.d:/etc/nginx/conf.d
    networks:
      - nat



networks:
  backend:
  nat: