
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydatabase
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate.format_sql: true

  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/mydatabase?authSource=admin

