spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  jwt:
    access:
      secret: accessabcdefg1234567891011121314151617181920
      expTime: 3000
    refresh:
      secret: refreshabcdefg1234567891011121314151617181920
      expTime: 6000


  data:
    mongodb:
      uri: mongodb://user:password@localhost:27017/mydatabase?authSource=admin

    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2-console



