spring:
  datasource:
    driver-class-name: org.h2.Driver #com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb #jdbc:mysql://littleriders.co.kr:23306/database?serverTimezone=UTC
    username: sa #user or root
    password: #password or rootpassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  jwt:
    access:
      secret: accessabcdefg1234567891011121314151617181920
      expTime: 120000
    refresh:
      secret: refreshabcdefg1234567891011121314151617181920
      expTime: 86400000


  data:
    mongodb:
      uri: mongodb://user:password@mongo.littleriders.co.kr:27017/mydatabase?authSource=admin

    redis:
      host: littleriders.co.kr
      port: 26379

  h2:
    console:
      enabled: true
      path: /h2-console



