server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mail:
    host: littleriders.co.kr
    port: 1025
    from: admin@littleriders.co.kr