spring:
  datasource:
    driver-class-name: org.h2.Driver #com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb #jdbc:mysql://littleriders.co.kr:33306/database?serverTimezone=UTC
    username: sa #user or root
    password: #password or rootpassword
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  jwt:
    access:
      secret: myaccesssecret1234
      expTime: 3000
    refresh:
      secret: myrefreshsecret1234
      expTime: 6000


  data:
    mongodb:
      uri: mongodb://user:password@mongo.littleriders.co.kr:37017/mydatabase?authSource=admin

    redis:
      host: littleriders.co.kr
      port: 36379

  h2:
    console:
      enabled: true
      path: /h2-console



